# Generated by Django 5.2.16 on 2026-07-28 07:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # pg_trgm must exist before a gin_trgm_ops index can be created.
        ('search', '0001_enable_pg_trgm'),
        ('clients', '0002_client_client_name_trgm_contact_contact_name_trgm'),
        ('projects', '0003_task_story_points_sprint_task_sprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='project_name_trgm'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', 'description', config='english'), name='project_fts'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='task_title_trgm'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'description', config='english'), name='task_fts'),
        ),
    ]
