# Generated by Django 5.2.16 on 2026-07-27 09:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0003_task_story_points_sprint_task_sprint_and_more'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('issue_date', models.DateField(blank=True, editable=False, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='projects.project')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_on', models.DateField()),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('upi', 'UPI'), ('card', 'Card'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'client'], name='billing_inv_status_9b5f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='billing_inv_due_dat_e51895_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False)), fields=('invoice_number',), name='invoice_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='invoice_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='invoice_amount_paid_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('invoice_number__isnull', False), ('issue_date__isnull', False), ('due_date__isnull', False)), _connector='OR'), name='invoice_issued_has_number_and_dates'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_at__isnull', False), ('status', 'paid')), models.Q(('status', 'paid'), _negated=True), _connector='OR'), name='invoice_paid_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), ('voided_at__isnull', False)), models.Q(('status', 'void'), _negated=True), _connector='OR'), name='invoice_void_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoice_item_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='invoice_item_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('tax_percent__gte', 0), ('tax_percent__lte', 100)), name='invoice_item_tax_range'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', '-received_on'], name='billing_pay_invoice_e6929b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
