# Generated by Django 5.2.16 on 2026-07-28 07:43

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # pg_trgm must exist before a gin_trgm_ops index can be created.
        ('search', '0001_enable_pg_trgm'),
        ('billing', '0002_refund_invoice_amount_refunded_payment_reconciled_at_and_more'),
        ('clients', '0002_client_client_name_trgm_contact_contact_name_trgm'),
        ('projects', '0004_project_project_name_trgm_project_project_fts_and_more'),
        ('quotations', '0002_quotation_quotation_title_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('invoice_number'), name='gin_trgm_ops'), name='invoice_number_trgm'),
        ),
    ]
