# Generated by Django 5.2.16 on 2026-07-27 07:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_capacity_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('40.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
