# Generated by Django 5.2.16 on 2026-07-28 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_name_trgm_contact_contact_name_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +91 98765 43210.', regex='^\\+?[0-9](?:[ \\-()]{0,2}[0-9]){6,14}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +91 98765 43210.', regex='^\\+?[0-9](?:[ \\-()]{0,2}[0-9]){6,14}$')]),
        ),
    ]
