# Generated by Django 5.2.16 on 2026-07-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status changed'), ('member_added', 'Member added'), ('member_removed', 'Member removed'), ('member_role_changed', 'Member role changed'), ('milestone_completed', 'Milestone completed'), ('milestone_reopened', 'Milestone reopened'), ('deleted', 'Deleted')], max_length=30)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveBigIntegerField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='activities__content_4ea3e7_idx')],
            },
        ),
    ]
