# Generated by Django 5.2.16 on 2026-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='verb',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status changed'), ('member_added', 'Member added'), ('member_removed', 'Member removed'), ('member_role_changed', 'Member role changed'), ('milestone_completed', 'Milestone completed'), ('milestone_reopened', 'Milestone reopened'), ('assigned', 'Assigned'), ('task_deleted', 'Task deleted'), ('sprint_started', 'Sprint started'), ('sprint_completed', 'Sprint completed'), ('escalated', 'Escalated'), ('payment_recorded', 'Payment recorded'), ('payment_deleted', 'Payment deleted'), ('payment_cleared', 'Payment cleared'), ('payment_bounced', 'Payment bounced'), ('refund_recorded', 'Refund recorded'), ('refund_deleted', 'Refund deleted'), ('reconciled', 'Reconciled'), ('deleted', 'Deleted')], max_length=30),
        ),
    ]
