# Generated by Django 5.2.16 on 2026-07-27 09:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(editable=False, max_length=20)),
                ('version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('terms', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_approved', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='clients.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='clients.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', 'created_by'], name='quotations__status_8cb74e_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['client', 'status'], name='quotations__client__ffd482_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['valid_until'], name='quotations__valid_u_5c5317_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('quote_number', 'version'), name='quotation_number_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='quotation_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', False), ('status', 'accepted')), models.Q(('status', 'accepted'), _negated=True), _connector='OR'), name='quotation_accepted_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quotation_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='quotation_item_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='quotation_item_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('tax_percent__gte', 0), ('tax_percent__lte', 100)), name='quotation_item_tax_range'),
        ),
    ]
