# Generated by Django 5.2.16 on 2026-07-28 07:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # pg_trgm must exist before a gin_trgm_ops index can be created.
        ('search', '0001_enable_pg_trgm'),
        ('clients', '0002_client_client_name_trgm_contact_contact_name_trgm'),
        ('tickets', '0002_seed_sla_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('subject'), name='gin_trgm_ops'), name='ticket_subject_trgm'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('subject', 'description', config='english'), name='ticket_fts'),
        ),
    ]
